services:

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: flackyfixer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./fixer_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LLM_PROVIDER: ${LLM_PROVIDER}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_OWNER: ${GITHUB_OWNER}
      GITHUB_REPO: ${GITHUB_REPO}
      POSTGRES_URL: ${POSTGRES_URL}

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data: